name: "Legal Entity Engagement Context Role"
description: Feedback
title: "A concise description"
assignees:
  - kmckenna-gleif
body:
  - type: markdown
    attributes:
      value: |
        2025-01-17_vLEI-EGF-v3.0-Legal-Entity-Engagement-Context-Role-vLEI-Credential-Framework-2024-Annual-Review_v1.4_draft.pdf
  - type: dropdown
    id: document
    attributes:
      label: Document
      options:
        - Legal-Entity-Engagement-Context-Role-vLEI-Credential-Framework
      default: 0
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: row-number
    attributes:
      label: Row number
      description: Row number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Please suggest a proposed update/edit that would resolve your question or comment.
    validations:
      required: true